### ISSUE TITLE
Lottie-web breaking change in 5.9.2

### ISSUE THREAD

**Issue by altruong** [mifi/react-lottie-player#70]
Lottie-web just updated their ts typing for loadAnimation parameter in their latest version v5.9.2
https://github.com/airbnb/lottie-web/commit/eb6d9a601e8ab724a1bcc285c5efe96243f52dc6

Which breaks the current version of react-lottie-player
<img width="625" alt="image" src="https://user-images.githubusercontent.com/55976444/162556073-cdb11dfe-fdfd-4f6b-8da9-e45f8c924595.png">

I've set my resolutions for lottie-web for v5.9.1 until its fixed, thanks!

**Comment by mifi** [comment]
Should this instead be fixed at lottie-web, and not here? Pardon my ignorance but I’m not an expert in ts

**Comment by altruong** [comment]
In the error that I have above, it says that in index.d.ts of this project, parameters `renderer`, `renderingSettings` and `audioFactory` is required but in the types from `AnimationConfig`, those parameters are optional so I'm not sure why TS is complaining. 
```ts
type LottieProps = React.DetailedHTMLProps<
    React.HTMLAttributes<HTMLDivElement>,
    HTMLDivElement
  > &
    Pick<AnimationConfig, 'loop' | 'renderer' | 'rendererSettings' | 'audioFactory'> & {
      play?: boolean
      goTo?: number
      speed?: number
      direction?: AnimationDirection
      segments?: AnimationSegment | AnimationSegment[]

      onComplete?: AnimationEventCallback
      onLoopComplete?: AnimationEventCallback
      onEnterFrame?: AnimationEventCallback
      onSegmentStart?: AnimationEventCallback
    } & ({ path?: string } | { animationData?: object })

```

To reproduce the error, you can try initialising the player in tsx where lottie-web is v5.9.2
```js
import Lottie from 'react-lottie-player';
<Lottie
    loop={false}
    play={true}
    animationData={link_to_file}
  />
```

**Comment by altruong** [comment]
Was it removed? I still see it in index.d.ts file in the latest version of [lottie-web github repo](https://github.com/airbnb/lottie-web/blob/master/index.d.ts). 

For reference: 
[lottie-web v5.9.4](https://github.com/airbnb/lottie-web/blob/master/index.d.ts)
[lottie-web v5.9.3](https://github.com/airbnb/lottie-web/blob/f7e567e00422ddb0f661ea9586a54df68e4c10d5/index.d.ts)

The only change I see is that this line (line 79 on lottie-web v5.9.3)
```ts
export type AnimationConfig<T extends 'svg' | 'canvas' | 'html' = 'svg'> = {}
```
was refactored to 
```ts
export type RendererType = 'svg' | 'canvas' | 'html';

export type AnimationConfig<T extends RendererType> = {}
```

And so this line also got changed (line 101 on lottie-web v5.9.3)
```ts
export type AnimationConfigWithPath = AnimationConfig & {
    path?: string;
}

export type AnimationConfigWithData = AnimationConfig & {
    animationData?: any;
}
```
to
```ts
export type AnimationConfigWithPath<T extends RendererType> = AnimationConfig<T> & {
    path?: string;
}

export type AnimationConfigWithData<T extends RendererType> = AnimationConfig<T> & {
    animationData?: any;
}
```

It's a small change and nothing got removed (unless im blind) so not sure why TS is complaining about

**Comment by monsonjeremy** [comment]
@altruong This package depends on `"lottie-web": "^5.7.6"` which means these are the `index.d.ts` contents: https://github.com/airbnb/lottie-web/blob/v5.7.6/index.d.ts#L79-L88
